version: 2
jobs:
  plan_terraform:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install make
          command: apk add --update make
      - run:
          name: Install python3
          command: apk add --update python3
      - run:
          name: Install terrascan
          command: pip3 install --upgrade terrascan
      - run:
          name: Validate terraform
          command: pwd && make plan_terraform
      - persist_to_workspace:
          root: .
          paths:
            - ./terraform/.terraform/*
  apply_terraform:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install make
          command: apk add --update make
      - run:
          name: Install python3
          command: apk add --update python3
      - run:
          name: Install terrascan
          command: pip3 install --upgrade terrascan
      - run:
          name: Deploy Lambda
          command: pwd && make apply_terraform

workflows:
  version: 2
  test_and_apply:
    jobs:
      - plan_terraform
      - apply_terraform:
          filters:
            branches:
              only: master
