policies:
  - name: iam-role-filter-policy
    resource: iam-role 
    description: |
      Retrieve list of IAM roles
    filters:
      - or:
          - type: value
            key: Name
            op: regex
            value: ".*"